// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taskflow.Infrastructure.Persistence;

#nullable disable

namespace Taskflow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813105104_updateMemberEntity")]
    partial class updateMemberEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taskflow.Domain.Project.ProjectAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Taskflow.Domain.User.UserAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "Taskflow.Domain.User.UserAggregate.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Password", "Taskflow.Domain.User.UserAggregate.Password#Password", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Password");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Username", "Taskflow.Domain.User.UserAggregate.Username#Username", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Username");
                        });

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Taskflow.Domain.Project.ProjectAggregate", b =>
                {
                    b.OwnsMany("Taskflow.Domain.Project.Entity.ProjectMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ProjectAggregateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Role")
                                .HasColumnType("integer");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectAggregateId");

                            b1.ToTable("ProjectMember");

                            b1.WithOwner()
                                .HasForeignKey("ProjectAggregateId");
                        });

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
